export const filter = {
    id: "",
    name: "",
    sku: "",
    code: "",
    price: "",
    critical_weight: "",
    type_id: "",
    measurement_id: "",
    country_id: "",
    is_active: null,
    warehouse_type_id: "",
    workplace_id: "",
    is_reworking: null,
    created_at: "",
    updated_at: "",
    from_date: '',
    to_date: '',
};
