export const filter = {
    id: '',
    search: '',
    client_id: '',
    console_number: '',
    application_id: '',
    start_date: '',
    stop_date: '',
    amount: '',
    paid: '',
    created_at: '',
    updated_at: '',
    from_date: '',
    to_date: '',
};
