export const model = {
    id: null,
    number: null,
    client: '',
    begin_date: '',
    status: '',
    conclusion_date: '',
    termination_date: '',
    sum: 0,
    remainder: 0,
    comment: '',
    created_at: '',
    updated_at: '',
    parent_id: '',
};