export const filter = {
    id: "",
    search: "",
    name: '',
    full_name: '',
    balance: '',
    sku: '',
    phone: '',
    email: '',
    object_name: '',
    district_id: '',
    quarter_id: '',
    object_street: '',
    object_home: '',
    object_corps: '',
    object_flat: '',
    comment: '',
    actual_address: '',
    type_id: '',
    legal_address: '',
    inn: '',
    mfo: '',
    okonx: '',
    oked: '',
    rkp_nds: '',
    created_at: '',
    updated_at: ''
};
