export const filter = {
    id: "",
    search: "",
    name: '',
    code: '',
    weight: '',
    nds: '',
    minimum_price: '',
    purchase_price: '',
    selling_price: '',
    minimum_balance: '',
    description: '',
    measurement_id: '',
    recycled: '',
    created_at: '',
    updated_at: '',
    deleted_at: '',
    vendor_code: '',
    country_id: '',
    warehouse_type_id: '',
    production: '',
    production_type: '',
    from_date: '',
    to_date: '',
};
