export const filter = {
    id: '',
    number: '',
    datetime: '',
    search: '',
    client_id: '',
    owner: '',
    amount: '',
    payed_sum: '',
    state_id: '',
    priority_id: '',
    created_at: '',
    begin_date: '',
    end_date: '',
    updated_at: '',
    contract_client_id: '',
    production_type: '',
    from_date: '',
    to_date: ''
};