export const filter = {
    id: '',
    search: '',
    number: '',
    datetime: '',
    client_id: '',
    client_phone: '',
    contract_client_id: '',
    status_id: '',
    console_number: '',
    amount: '',
    object_name: '',
    district_id: '',
    quarter_id: '',
    object_address: '',
    object_street: '',
    object_home: '',
    object_corps: '',
    object_flat: '',
    created_at: '',
    updated_at: '',
    from_date: '',
    to_date: '',
    status_by_payment: 'all',
};
