export const buy_model = {
    id: undefined,
    provider_id: "",
    contract_provider_id: "",
    paid: "",
    date: "",
    total_price: 0,
    paid_price: "",
    comment: "",
    status_id: "",
    object_id: "",
    object_type: "",
    is_warehouse: "",
    created_at: "",
    updated_at: "",
    buy_notification_id: null,
};