export const filter = {
    id: '',
    number: '',
    datetime: '',
    user_id: '',
    provider_id: '',
    contract_provider_id: '',
    paid: '',
    date: '',
    total_price: '',
    paid_price: '',
    comment: '',
    status_id: '',
    object_id: '',
    object_type: '',
    is_warehouse: '',
    created_at: '',
    updated_at: '',
    search: '',
    from_date: '',
    to_date: ''
};